ShopBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: ShopBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        categoryNameEs:
            type: string
            length: 255
        categoryNameEn:
            type: string
            length: 255
        turn:
            type: integer
    oneToMany:
        products:
            targetEntity: Product
            mappedBy: category
    lifecycleCallbacks: {  }
