ShopBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: ShopBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        companyName:
            type: string
            length: 255
        companyAddress:
            type: string
            length: 255
        tel:
            type: string
            length: 255
    oneToOne:
        cart:
            targetEntity: Cart
            mappedBy: user
    oneToMany:
        orderInfos:
            targetEntity: OrderInfo
            mappedBy: user
    lifecycleCallbacks: {  }
