category_index:
    path:     /
    defaults: { _controller: "ShopBundle:Category:index" }
    methods:  GET

category_show:
    path:     /{id}/show
    defaults: { _controller: "ShopBundle:Category:show" }
    methods:  GET

category_new:
    path:     /new
    defaults: { _controller: "ShopBundle:Category:new" }
    methods:  [GET, POST]

category_edit:
    path:     /{id}/edit
    defaults: { _controller: "ShopBundle:Category:edit" }
    methods:  [GET, POST]

category_delete:
    path:     /{id}/delete
    defaults: { _controller: "ShopBundle:Category:delete" }
    methods:  DELETE

category_turn_up:
    path:     /{id}/turn_up
    defaults: { _controller: "ShopBundle:Category:turnUp" }

category_turn_down:
    path:     /{id}/turn_down
    defaults: { _controller: "ShopBundle:Category:turnDown" }

